#data.py

campusMappings = {
    "Centennial Gate": "CEN",
    "Central Podium Levels": "CPD", 
    "Chi Wah Learning Commons": "CHI",
    "Chong Yuet Ming Amenities Center": "CYM",
    "Composite Building": "COM",
    "Elliott Hall": "ELL",
    "Estates Building": "EST",
    "Fong Shu Chuen Amenities Center": "FON",
    "Faculty of Medicine Building": "FAM",
    "Graduate House": "GRA",
    "Haking Wong Building": "HAK",
    "Hui Oi Chow Building": "HUI",
    "James Hsuioung Lee Building": "JHL",
    "KK Leung Building": "KKL",
    "Kadoorie Biological Sciences Building": "KAD",
    "K.K. Leung Building": "KLB",
    "Knowles Building": "KNO",
    "Lee Shau Kee Lecture Centre": "LSK",
    "Li Ka Shing Faculty of Medicine": "LKS",
    "Library Building": "LIB",
    "Law Library": "LAW",
    "Loke Yew Hall": "LOK",
    "Main Building": "MAI",
    "May Hall": "MAY",
    "Meng Wah Complex": "MWC",
    "Pao Siu Loong Building": "PAO",
    "Rayson Huang Theatre": "RHT",
    "Run Run Shaw Building": "RUN",
    "Sassoon Road Halls": "SRH",
    "Swire Hall": "SWH",
    "TT Tsui Building": "TTT",
    "The Jockey Club Tower": "JCK",
    "Wong Chue Meng Building": "WCM",
    "HKU B-Active": "HKA",
    "Stanley Ho Sports Center": "SHS",
    "Queen Mary Hospital": "QMH",
    "University Hall": "UH",
    "JCSV II": "JCV2",
    "JCSV III": "JCV3",
    "Jockey Club Student Village 3": "JCV3",  
    "Jockey Club Student Village 2": "JCV2",  
    "Jockey Club Student Village III": "JCV3", 
    "Jockey Club Student Village II": "JCV2", 
    "Ricci Hall": "RIC",
    "St. John's College": "SJC",
    "Starr Hall": "STA",
}

campusReversedMappings = {
    'CEN': 'Centennial Gate', 
    'CPD': 'Central Podium Levels', 
    'CHI': 'Chi Wah Learning Commons', 
    'CYM': 'Chong Yuet Ming Amenities Center', 
    'COM': 'Composite Building', 
    'ELL': 'Elliott Hall', 
    'EST': 'Estates Building', 
    'FON': 'Fong Shu Chuen Amenities Center', 
    'FAM': 'Faculty of Medicine Building', 
    'GRA': 'Graduate House', 
    'HAK': 'Haking Wong Building', 
    'HUI': 'Hui Oi Chow Building', 
    'JHL': 'James Hsuioung Lee Building', 
    'KKL': 'KK Leung Building', 
    'KAD': 'Kadoorie Biological Sciences Building', 
    'KLB': 'K.K. Leung Building', 
    'KNO': 'Knowles Building', 
    'LSK': 'Lee Shau Kee Lecture Centre', 
    'LKS': 'Li Ka Shing Faculty of Medicine', 
    'LIB': 'Library Building', 
    'LAW': 'Law Library', 
    'LOK': 'Loke Yew Hall', 
    'MAI': 'Main Building', 
    'MAY': 'May Hall', 
    'MWC': 'Meng Wah Complex', 
    'PAO': 'Pao Siu Loong Building', 
    'RHT': 'Rayson Huang Theatre', 
    'RUN': 'Run Run Shaw Building', 
    'SRH': 'Sassoon Road Halls', 
    'SWH': 'Swire Hall', 
    'TTT': 'TT Tsui Building', 
    'JCK': 'The Jockey Club Tower', 
    'WCM': 'Wong Chue Meng Building', 
    'HKA': 'HKU B-Active', 
    'SHS': 'Stanley Ho Sports Center', 
    'QMH': 'Queen Mary Hospital', 
    'UH': 'University Hall', 
    'JCV2': 'JCSV II', 
    'JCV3': 'JCSV III', 
    'JCV3': 'Jockey Club Student Village 3', 
    'JCV2': 'Jockey Club Student Village 2', 
    'JCV3': 'Jockey Club Student Village III', 
    'JCV2': 'Jockey Club Student Village II', 
    'RIC': 'Ricci Hall', 
    'SJC': 'St. John\'s College', 
    'STA': 'Starr Hall'
    }

# Adjacency list representation of the weighted bidirectional graph
campusGraph = {
    'SJC': [('RIC', 4), ('STA', 5), ('JCV2', 2), ('HKA', 15), ('JCV3', 14), ('SRH', 21)],
    'RIC': [('SJC', 4), ('STA', 1), ('JCV3', 14)],
    'STA': [('SJC', 5), ('RIC', 1), ('CEN', 4), ('CPD', 6), ('HKA', 10), ('SRH', 28)],
    'JCV2': [('SJC', 2), ('JCV3', 13)],
    'JCV3': [('SJC', 14), ('RIC', 14), ('JCV2', 13), ('SRH', 25)],
    'SRH': [('JCV3', 25), ('SJC', 21), ('STA', 28), ('SHS', 10)],
    'CEN': [('STA', 4), ('CPD', 2), ('CHI', 4), ('KAD', 3)],
    'CPD': [('STA', 6), ('CEN', 2), ('COM', 4), ('MWC', 11), ('JCK', 2), ('RHT', 6), ('LIB', 5), ('LSK', 1), ('RUN', 1), ('HAK', 9)],
    'CHI': [('CEN', 4), ('CYM', 8), ('JCK', 1)],
    'CYM': [('CHI', 8), ('ELL', 4), ('KKL', 2), ('MAP', 2), ('MWC', 2), ('RHT', 2), ('LIB', 4)],
    'ELL': [('CYM', 4), ('MAY', 1)],
    'KKL': [('CYM', 2), ('SWH', 2), ('TTT', 2)],
    'SWH': [('KKL', 2), ('TTT', 1)],
    'MAI': [('PAO', 3), ('LIB', 3)],
    'SHS': [('SRH', 10), ('LKS', 10)],
    'LKS': [('SHS', 10), ('QMH', 5)],
    'LIB': [('CPD', 5), ('CYM', 4), ('MAI', 3), ('RHT', 4)],
    'UH': [('QMH', 10)],
    'QMH': [('UH', 10), ('LKS', 5), ('FAM', 5)],
    'RHT': [('CPD', 6), ('CYM', 2), ('LIB', 4), ('KNO', 2), ('JHL', 2)],
    'LSK': [('CPD', 1)],
    'JCK': [('CPD', 2), ('LAW', 1), ('CHI', 1)],
    'KAD': [('CEN', 3)],
    'FAM': [('QMH', 5)],
    'RUN': [('CPD', 1)],
    'JHL': [('RHT', 2), ('COM', 2), ('HUI', 6)],
    'HAK': [('COM', 2), ('CPD', 9)],
    'HUI': [('JHL', 6), ('GRA', 5)],
    'GRA': [('MWC', 7), ('HUI', 5)],
    'MWC': [('CYM', 2), ('WCM', 2), ('CPD', 11), ('GRA', 7)],
    'WCM': [('MWC', 2)],
    'TTT': [('KKL', 2), ('SWH', 1)],
    'HKA': [('SJC', 15), ('STA', 10)],
    'COM': [('CPD', 4), ('JHL', 2), ('HAK', 2)],
    'MAP': [('CYM', 2)],
    'MAY': [('ELL', 1)],
    'PAO': [('MAI', 3)],
    'KNO': [('RHT', 2)],
    'LAW': [('JCK', 1)]
}